/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppCard: typeof import('./../src/components/RepoCard/AppCard.vue')['default']
    RepoActive: typeof import('./../src/components/RepoCard/RepoActive.vue')['default']
    RepoCard: typeof import('./../src/components/RepoCard/RepoCard.vue')['default']
    RepoInfoDrawer: typeof import('./../src/components/RepoCard/RepoInfoDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UnoCSSIconButton: typeof import('./../src/components/Icon/UnoCSSIconButton.vue')['default']
  }
}
